#!/usr/bin/env bash
#
# theme/generate.sh - render theme/palette.conf into per-application config
# fragments inside stow/, so that stow stays the only deploy mechanism.
#
# Each target program gets a "theme" fragment that its hand-written config
# pulls in via that program's own include mechanism (sway `include`, foot
# `include=`, fuzzel `include=`, CSS `@import`). Generated fragments are
# gitignored build artifacts: edit theme/palette.conf instead.
#
# Run standalone or via bootstrap.sh. Exits 0 and prints one line per file.

set -euo pipefail

THEME_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname -- "$THEME_DIR")"
PALETTE="$THEME_DIR/palette.conf"
STOW_DIR="$REPO_DIR/stow"

# Per-machine overrides, if bootstrap has already written them.
LOCAL_CONF="${SYOS_LOCAL_CONF:-$HOME/.config/syos/local.conf}"

CHANGED=0

die() {
	printf 'theme/generate.sh: %s\n' "$1" >&2
	exit 1
}

[[ -f "$PALETTE" ]] || die "palette not found: $PALETTE"

# --- palette parsing ----------------------------------------------------
# Parsed rather than sourced: palette.conf is data, and treating it as data
# keeps a stray backtick in a comment from executing.

declare -A P

read_kv_file() {
	local file="$1" key value
	while IFS='=' read -r key value; do
		key="${key%%#*}"
		key="${key//[[:space:]]/}"
		[[ -z "$key" ]] && continue
		value="${value%$'\r'}"
		value="${value#"${value%%[![:space:]]*}"}"
		value="${value%"${value##*[![:space:]]}"}"
		P["$key"]="$value"
	done <"$file"
}

read_kv_file "$PALETTE"

if [[ -f "$LOCAL_CONF" ]]; then
	read_kv_file "$LOCAL_CONF"
fi

# Raw 6-digit hex, validated so a typo in the palette fails here rather than
# silently producing a config the compositor refuses to load.
hex() {
	local key="$1" value="${P[$1]:-}"
	[[ -n "$value" ]] || die "palette key '$key' is not set"
	[[ "$value" =~ ^[0-9a-fA-F]{6}$ ]] || die "palette key '$key' is not 6-digit hex: '$value'"
	printf '%s' "$value"
}

# #RRGGBB for sway and CSS.
css() { printf '#%s' "$(hex "$1")"; }

# RRGGBBAA for fuzzel, which always wants an explicit alpha channel.
rgba() { printf '%sff' "$(hex "$1")"; }

val() {
	local key="$1" value="${P[$1]:-}"
	[[ -n "$value" ]] || die "palette key '$key' is not set"
	printf '%s' "$value"
}

FONT_FAMILY="$(val FONT_FAMILY)"
FONT_FALLBACK="$(val FONT_FALLBACK)"
# SYOS_FONT_SIZE comes from local.conf and wins over the palette default.
FONT_SIZE="${P[SYOS_FONT_SIZE]:-$(val FONT_SIZE_DEFAULT)}"
BAR_HEIGHT="$(val BAR_HEIGHT)"
BORDER_WIDTH="$(val BORDER_WIDTH)"

[[ "$FONT_SIZE" =~ ^[0-9]+(\.[0-9]+)?$ ]] || die "font size is not numeric: '$FONT_SIZE'"

# --- emit helper --------------------------------------------------------
# Writes stdin to $1 only when the content actually differs, so re-running
# bootstrap does not churn mtimes and the "no changes" run stays honest.

emit() {
	local target="$1" tmp
	mkdir -p "$(dirname -- "$target")"
	tmp="$(mktemp)"
	cat >"$tmp"
	if [[ -f "$target" ]] && cmp -s "$tmp" "$target"; then
		rm -f "$tmp"
		printf '  unchanged  %s\n' "${target#"$REPO_DIR"/}"
		return 0
	fi
	mv "$tmp" "$target"
	chmod 0644 "$target"
	CHANGED=$((CHANGED + 1))
	printf '  wrote      %s\n' "${target#"$REPO_DIR"/}"
}

BANNER="GENERATED by theme/generate.sh from theme/palette.conf - do not edit."

# --- sway ---------------------------------------------------------------

emit "$STOW_DIR/sway/.config/sway/theme.conf" <<EOF
# $BANNER

font pango:$FONT_FAMILY, $FONT_FALLBACK, monospace $FONT_SIZE

# Zero gaps, hairline borders, no titlebars beyond the tab strip.
default_border pixel $BORDER_WIDTH
default_floating_border pixel $BORDER_WIDTH
titlebar_border_thickness 0
gaps inner 0
gaps outer 0

# Solid background color, read by the swaybg exec in the main config.
set \$syos_bg $(css BG)

#                       border            background        text              indicator         child_border
client.focused          $(css BORDER_FOCUS)           $(css BG_SEL)           $(css FG)           $(css ACCENT)           $(css BORDER_FOCUS)
client.focused_inactive $(css BORDER)           $(css BG_ALT)           $(css FG_DIM)           $(css BORDER)           $(css BORDER)
client.unfocused        $(css BORDER)           $(css BG)           $(css FG_DIM)           $(css BORDER)           $(css BORDER)
client.urgent           $(css URGENT)           $(css URGENT)           $(css BG)           $(css URGENT)           $(css URGENT)
client.placeholder      $(css BORDER)           $(css BG)           $(css FG_DIM)           $(css BORDER)           $(css BORDER)
client.background       $(css BG)
EOF

# --- foot ---------------------------------------------------------------
# foot include files carry their own section scope, so sections are explicit.
# Colors are bare hex with no leading '#'.

emit "$STOW_DIR/foot/.config/foot/theme.ini" <<EOF
# $BANNER

[main]
font=$FONT_FAMILY:size=$FONT_SIZE, $FONT_FALLBACK:size=$FONT_SIZE

[colors]
background=$(hex BG)
foreground=$(hex FG)
selection-background=$(hex BG_SEL)
selection-foreground=$(hex FG)
urls=$(hex ACCENT)

regular0=$(hex ANSI_BLACK)
regular1=$(hex ANSI_RED)
regular2=$(hex ANSI_GREEN)
regular3=$(hex ANSI_YELLOW)
regular4=$(hex ANSI_BLUE)
regular5=$(hex ANSI_MAGENTA)
regular6=$(hex ANSI_CYAN)
regular7=$(hex ANSI_WHITE)

bright0=$(hex ANSI_BRIGHT_BLACK)
bright1=$(hex ANSI_BRIGHT_RED)
bright2=$(hex ANSI_BRIGHT_GREEN)
bright3=$(hex ANSI_BRIGHT_YELLOW)
bright4=$(hex ANSI_BRIGHT_BLUE)
bright5=$(hex ANSI_BRIGHT_MAGENTA)
bright6=$(hex ANSI_BRIGHT_CYAN)
bright7=$(hex ANSI_BRIGHT_WHITE)
EOF

# --- waybar -------------------------------------------------------------
# Bar height lives here rather than in config.jsonc: config.jsonc sets
# "height": 0 (auto) so the palette stays the single source of truth.

emit "$STOW_DIR/waybar/.config/waybar/theme.css" <<EOF
/* $BANNER */

@define-color bg $(css BG);
@define-color bg_alt $(css BG_ALT);
@define-color bg_sel $(css BG_SEL);
@define-color fg $(css FG);
@define-color fg_dim $(css FG_DIM);
@define-color accent $(css ACCENT);
@define-color accent_dim $(css ACCENT_DIM);
@define-color warn $(css WARN);
@define-color urgent $(css URGENT);
@define-color border $(css BORDER);

* {
	font-family: "$FONT_FAMILY", "$FONT_FALLBACK", monospace;
	font-size: ${FONT_SIZE}pt;
}

window#waybar {
	min-height: ${BAR_HEIGHT}px;
}
EOF

# --- fuzzel -------------------------------------------------------------
# fuzzel colors are RRGGBBAA.

emit "$STOW_DIR/fuzzel/.config/fuzzel/theme.ini" <<EOF
# $BANNER

[main]
font=$FONT_FAMILY:size=$FONT_SIZE

[colors]
background=$(rgba BG)
text=$(rgba FG)
prompt=$(rgba FG_DIM)
placeholder=$(rgba FG_DIM)
input=$(rgba FG)
match=$(rgba ACCENT)
selection=$(rgba BG_SEL)
selection-text=$(rgba FG)
selection-match=$(rgba ACCENT)
border=$(rgba BORDER_FOCUS)

[border]
width=$BORDER_WIDTH
radius=0
EOF

if [[ "$CHANGED" -eq 0 ]]; then
	printf 'theme: up to date (%s, %spt)\n' "$FONT_FAMILY" "$FONT_SIZE"
else
	printf 'theme: %d fragment(s) regenerated (%s, %spt)\n' "$CHANGED" "$FONT_FAMILY" "$FONT_SIZE"
fi
